### PR TITLE
Build failing due to missing dependency (gradle-aws-s3-sync:0.4)

### PR DESCRIPTION
**Pull request by pereferrera**
Replaced failing maven repo by conjars and updated dependency accordingly.

### CODE REVIEW

**Comment by fs111** [comment]
Can you elaborate what's failing for you? The repo works fine from here.

**Comment by pereferrera** [comment]
Hello André,
The issue is described here: https://groups.google.com/forum/#!topic/pattern-user/GdVXqkdr6T8

Perhaps you have the dependency cached in your local maven?

**Comment by fs111** [comment]
There must be something wrong between you and the cloudbees repo. It works for me from 2 totally different networks without problems:

$ curl -I http://repository-monochromeroad.forge.cloudbees.com/release/com/monochromeroad/gradle/gradle-aws-s3-sync/0.4/gradle-aws-s3-sync-0.4.jar
HTTP/1.1 200 OK
Date: Thu, 06 Mar 2014 13:29:04 GMT
Server: Apache/2.4.7 (Unix) SVN/1.8.5
Last-Modified: Wed, 13 Jun 2012 09:03:33 GMT
ETag: "5fab-4c256db8cb82f"
Accept-Ranges: bytes
Content-Length: 24491
Content-Type: application/java-archive

$ curl -I http://repository-monochromeroad.forge.cloudbees.com/release/com/monochromeroad/gradle/gradle-aws-s3-sync/0.4/gradle-aws-s3-sync-0.4.pom
HTTP/1.1 200 OK
Date: Thu, 06 Mar 2014 13:29:13 GMT
Server: Apache/2.4.7 (Unix) SVN/1.8.5
Last-Modified: Wed, 13 Jun 2012 09:03:33 GMT
ETag: "333-4c256db9395ba"
Accept-Ranges: bytes
Content-Length: 819

**Comment by pereferrera** [comment]
Hi André,

It also works for me now. It has been definitely failing up to now, as you can see from the gradle trace... No idea what happened, maybe an outage.

**Comment by fs111** [comment]
mtr --report -n repository-monochromeroad.forge.cloudbees.com is ususally a good way to find network bumps along the way.

**Comment by pereferrera** [comment]
Thanks!

Consider this issue closed then.

**Pull request closed without merging**
